### ISSUE TITLE
requests.exceptions.SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by oryonatan** [deanoemcke/humblebundle-meet-metacritic#1]
Traceback (most recent call last):
  File "humbleMetacritic.py", line 163, in <module>
    gamelist = fetch_humble_gameslist()
  File "humbleMetacritic.py", line 105, in fetch_humble_gameslist
    client.login(humble_email, humble_pass)
  File "build/bdist.linux-x86_64/egg/humblebundle/decorators.py", line 20, in wrap
  File "build/bdist.linux-x86_64/egg/humblebundle/client.py", line 114, in login
  File "build/bdist.linux-x86_64/egg/humblebundle/client.py", line 317, in _request
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

**Comment by vorburger** [comment]
see e.g. https://github.com/google/clusterfuzz-tools/issues/144 and https://github.com/jakubroztocil/httpie/issues/315
